import { createApp, shallowRef } from 'vue'
import { connectDevframe } from 'devframe/client'
import { connectionKey, type ExplorerConnection } from './connection'
import type { ExplorerState } from '../protocol'
import { defineNuxtPlugin } from '#app'
import Inspector from './Inspector.vue'
// @ts-ignore generated by the module only during development
import css from '#build/vue-explorer-style'

export default defineNuxtPlugin((nuxtApp) => {
  let dispose: (() => void) | undefined
  nuxtApp.hook('app:mounted', () => {
    let disposed = false
    const connection: ExplorerConnection = {
      client: null,
      status: shallowRef('connecting'),
      state: shallowRef<ExplorerState>({ selection: null, requests: [] }),
      select: () => {},
    }
    const host = document.createElement('vue-explorer')
    host.dataset.vueExplorer = 'true'
    document.body.appendChild(host)
    const shadow = host.attachShadow({ mode: 'open' })
    const style = document.createElement('style')
    style.textContent = css
    const root = document.createElement('div')
    shadow.append(style, root)
    const app = createApp(Inspector)
    app.provide(connectionKey, connection)
    app.mount(root)
    const originalFetch = window.fetch
    const originalDollarFetch = globalThis.$fetch
    let wrappedFetch: typeof fetch | undefined
    let wrappedDollarFetch: typeof globalThis.$fetch | undefined
    dispose = () => {
      disposed = true
      if (window.fetch === wrappedFetch) window.fetch = originalFetch
      if (globalThis.$fetch === wrappedDollarFetch) globalThis.$fetch = originalDollarFetch
      connection.client?.close?.()
      app.unmount()
      host.remove()
    }
    void (async () => {
      try {
        const client = await connectDevframe({ baseURL: '/__vue_explorer/', callTimeout: 5000 })
        if (disposed) {
          client.close?.()
          return
        }
        connection.client = client
        if (!client.isTrusted) {
          const response = await originalFetch('/__vue_explorer/__auth')
          if (!response.ok) throw new Error('Local Devframe authentication failed.')
          const { code } = await response.json()
          if (!(await client.requestTrustWithCode(code)))
            throw new Error('Devframe trust exchange failed.')
        }
        const shared = await client.scope('vue-explorer').rpc.sharedState('state')
        if (disposed) {
          client.close?.()
          return
        }
        connection.state.value = shared.value() as ExplorerState
        shared.on('updated', (value) => {
          connection.state.value = value as ExplorerState
        })
        connection.select = (selection) =>
          shared.mutate((draft) => {
            draft.selection = selection
          })
        connection.status.value = client.status
        client.events.on('connection:status', (status) => {
          connection.status.value = status
        })
        wrappedFetch = async (input, init) => {
          const url = new URL(
            input instanceof Request ? input.url : String(input),
            window.location.href,
          )
          // Capture only local API metadata; never retain bodies, headers or query strings.
          if (url.origin !== window.location.origin || !url.pathname.startsWith('/api/'))
            return originalFetch(input, init)
          const started = performance.now()
          let status = 0
          let handler: string | undefined
          let serverDuration: number | undefined
          try {
            const response = await originalFetch(input, init)
            status = response.status
            const encodedHandler = response.headers.get('X-Vue-Explorer-Handler')
            if (encodedHandler) {
              try {
                handler = decodeURIComponent(encodedHandler)
              } catch {}
            }
            const timing = response.headers
              .get('Server-Timing')
              ?.match(/vue-explorer;dur=([\d.]+)/)?.[1]
            if (timing) serverDuration = Number(timing)
            return response
          } finally {
            void client
              .call('vue-explorer:record-request', {
                id: crypto.randomUUID(),
                path: url.pathname,
                method: init?.method || (input instanceof Request ? input.method : 'GET'),
                status,
                duration: performance.now() - started,
                timestamp: Date.now(),
                handler,
                serverDuration,
              })
              .catch(() => {})
          }
        }
        window.fetch = wrappedFetch
        // Nitro's narrowed $fetch type omits ofetch's second global-options argument.
        const createFetch = originalDollarFetch.create as unknown as (
          defaults: Record<string, never>,
          options: { fetch: typeof fetch },
        ) => typeof originalDollarFetch
        wrappedDollarFetch = createFetch({}, { fetch: wrappedFetch })
        globalThis.$fetch = wrappedDollarFetch
      } catch (error) {
        if (!disposed)
          connection.status.value = error instanceof Error ? error.message : 'Connection failed'
      }
    })()
  })
  if (import.meta.hot) import.meta.hot.dispose(() => dispose?.())
})
